name: Python - Continuous Integration

on:
  push:
    branches:
      - "master"
      - "develop"
      - "hotfix/**"
      - "feature/**"
      - "renovate/**"
      - "dependabot/**"

jobs:
  ci:
    name: Python - Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check
        run: make check
      - name: Format
        run: make format
